### ISSUE TITLE
Registers exhausted with lots of pointer use

### ISSUE THREAD

**Issue by dylanmckay** [avr-llvm/llvm#1]
This bug description is what I can piece together from `CalcSpillWeights.cpp` and [this email](http://sourceforge.net/p/avr-llvm/mailman/message/31038226/).

When compiling functions for AVR that contain much pointer use, the register allocator fail with the error `ran out of registers`. A hack is currently in place so that any function marked unspillable that has a lot of pointer access will be forced into being spillable.

The error message is as follows:
```
LLVM ERROR: ran out of registers during register allocation
```
Here is the code comment where the hack is implemented (in `lib/CodeGen/CalcSpillWeights.cpp`): It was commited in [r247](http://sourceforge.net/p/avr-llvm/code/247).

``` cpp
// HACK HACK: This is a workaround until PR14879 gets fixed!
// This code allows us to compile memory intensive functions when only the Z
// register is available, otherwise we get the "Ran out of registers ..."
// assertion inside the regalloc.
// Here we avoid marking as not spillable live intervals that use the
// PTRDISPREGS class and have a size greater than 8, smaller ones
// get filtered out, generating better code.
```

An old llvmdev mailing list thread discussing the hack can be found [here](http://lists.cs.uiuc.edu/pipermail/llvmdev/2012-December/thread.html#57123), and continued [here](http://lists.cs.uiuc.edu/pipermail/llvmdev/2013-January/057664.html).

An LLVM bug is filed for the issue - see LLVM BugZilla bug [14879](https://llvm.org/bugs/show_bug.cgi?id=14879).

**Comment by dylanmckay** [comment]
The code was commited in [r247](http://sourceforge.net/p/avr-llvm/code/247).

**Comment by dylanmckay** [comment]
It would be nice to properly fix this hack because it is one of the few files we touch outside of `lib/Target/AVR`, and is an (albeit small) maintenance burden when updating LLVM to master/

**Comment by dylanmckay** [comment]
I found a set of mailing list messages from one of the previous authors detailing the problem [here](http://lists.cs.uiuc.edu/pipermail/llvmdev/2013-January/057664.html)

**Comment by dylanmckay** [comment]
The official LLVM bug report [14879](http://llvm.org/bugs/show_bug.cgi?id=14879)

**Comment by dylanmckay** [comment]
Reproduction code:

``` cpp
struct ss
{
  int a;
  int b;
  int c;
};
void loop(struct ss *x, struct ss **y, int z)
{
  int i;
  for (i=0; i<z; ++i)
  {
    x->c += y[i]->b;
  }
}
```

**Comment by dylanmckay** [comment]
Issue #37 is now closed, so we can now reproduce this error. The snippet does indeed cause a "ran out of registers" error.

**Comment by dylanmckay** [comment]
I have removed the hack from the tree. A proper fix needs to be created.

**Comment by dylanmckay** [comment]
The error is also triggered in the unit test `test/CodeGen/AVR/dynalloca.ll`.

**Comment by dylanmckay** [comment]
@agnat I removed part of the hack in 7f4cc26311e08d90c9296897beff116e96066bfd. Do you want to revert it and see where it gets us?

**Comment by agnat** [comment]
Nah, no worries. Now that I know where the missing pieces are... ;)

**Comment by dylanmckay** [comment]
A workaround is to change the optimisation level to zero. This could break the build as #145 stops us from using another allocator but `RegAllocGreedy`.

**Comment by dylanmckay** [comment]
I reapplied the hack in f07a0fd49040e682ec24e9e02e0ee3b6a5cc5f0a.

I'm fairly certain that the Y register preservation hack and the constrained register class hacks are separate entities.

**Comment by dylanmckay** [comment]
Added a test for this locally

b705c4bdb2558a17931644ddf2dd705998f92cb3

**Comment by dylanmckay** [comment]
I think this is triggered by this `isSpillable()` check in `RegAllocGreedy.cpp`. When I remove the check, the file compiles successfully.

This makes sense, because the existing hacky workaround works by explicitly marking all small live intervals as spillable, even if they were previously marked unspillable.

[RegAllocGreedy.cpp](https://github.com/avr-llvm/llvm/blob/b705c4bdb2558a17931644ddf2dd705998f92cb3/lib/CodeGen/RegAllocGreedy.cpp#L2593)

Looking at the generated assembly, we are infact spilling a pointer register when I remove the check. The comment on the original BugZilla mentions that it should be perfectly possible to avoid spilling by simply copying the `PTRREG` to one of the many `DREGS`. The problem is likely that LLVM sees that there are no free `PTRREGS` to copy to, and doesn't take into account we can save/restore to another register class.

This makes sense, because in most backends that LLVM supports, there isn't much overlap between register classes.

The best fix may be to simple support saving/restoring to alternative register classes where possible.

**Comment by dylanmckay** [comment]
I have a fix pending the test suite which attempts to fix this by attempting to spill live intervals before bailing out like what we do currently.

**Comment by dylanmckay** [comment]
I have merged the fix. Once [reviews.llvm.org](reviews.llvm.org) comes back online, I'll upstream the fix.

**Comment by dylanmckay** [comment]
Fix merged upstream in [r283838](http://llvm.org/viewvc/llvm-project?view=revision&revision=283838)
