### ISSUE TITLE
Implement FRMIDX pseudo instruction

### ISSUE THREAD

**Issue by dylanmckay** [avr-llvm/llvm#114]
The instruction is supposed to be lower into an `movw` + `adiw`.

See `AVRInstrInfo.td` for more info.

**Comment by agnat** [comment]
I believe this is already handled [here](https://github.com/avr-llvm/llvm/blob/avr-support/lib/Target/AVR/AVRRegisterInfo.cpp#L125).

Maybe we should close the ... pseudo issues. Not that some helpful nerd starts working on them like I did with the asm-parser tickets...

**Comment by dylanmckay** [comment]
I opened these up without properly investigating them. I'll have a proper look now.

> Not that some helpful nerd starts working on them like I did with the asm-parser tickets

That would be convenient ;)

**Comment by dylanmckay** [comment]
I closed this one but left the following three open.

* #115 is stopping us from compiling Arduino
* #112 and #113 will cause confusing errors when hit
