### ISSUE TITLE
Support Arduino

### ISSUE THREAD

**Issue by dylanmckay** [avr-llvm/llvm#139]
We need to be able to compile the entire Arduino core.

Note that USB was not enabled when I attempted to build these files, so many files have been `#ifdef`'d out because `-DUSBCON` was not defined.

C++ files (and whether we can compile them without errors):
- [x] CDC.cpp
- [x] HID.cpp
- [x] HardwareSerial.cpp
- [x] HardwareSerial0.cpp
- [x] HardwareSerial1.cpp
- [x] HardwareSerial2.cpp
- [x] HardwareSerial3.cpp
- [x] IPAddress.cpp
- [x] Print.cpp
- [x] Stream.cpp
- [x] Tone.cpp
- [x] USBCore.cpp
- [x] WInterrupts.c
- [x] WMath.cpp
- [x] WString.cpp
- [x] abi.cpp
- [x] hooks.c
- [x] main.cpp
- [x] new.cpp
- [x] wiring.c
- [x] wiring_analog.c
- [x] wiring_digital.c
- [x] wiring_pulse.c
- [x] wiring_shift.c

[Here](https://gist.github.com/dylanmckay/3bbbabb912d16e1a39f1) is a Gist containing all of the C++ Arduino core files compiled into LLVM IR.

**Comment by paulobarcelos** [comment]
+1

**Comment by dylanmckay** [comment]
There's only one file left to fix - `Stream.cpp` - for which I have a fix, I just need to update a few tests.

**Comment by dylanmckay** [comment]
As of eb79a907be4b70953586e27124d9ac5009ec8797 (which was blocking `Stream.cpp`), we can now completely compile the Arduino core.

**Comment by dylanmckay** [comment]
This is not quite true as of today - see #149.
