### ISSUE TITLE
Fix CodeGen unit tests

### ISSUE THREAD

**Issue by dylanmckay** [avr-llvm/llvm#27]
Upon forking the original AVR-LLVM repository, a set of AVR tests were imported in the process.

They currently do not pass, and so they need to be fixed.

All of the imported tests exist in `test/CodeGen/AVR`.

Here are the tests:
- [x] add.ll
- [x] alloca.ll
- [x] and.ll
- [x] brind.ll
- [x] call.ll
- [x] cmp.ll
- [x] com.ll
- [x] directmem.ll
- [x] dynalloca.ll
- [x] frame.ll
- [ ] inline-asm.ll
- [x] interrupts.ll
- [x] io.ll
- [ ] load.ll
- [x] mul.ll
- [x] neg.ll
- [x] or.ll
- [ ] progmem.ll
- [x] return.ll
- [x] sext.ll
- [ ] store.ll
- [x] sub.ll
- [x] trunc.ll
- [x] varargs.ll
- [x] xor.ll
- [x] zext.ll

**Comment by RandomInsano** [comment]
Can we put this sort of thing in the Wiki or a standalone file?

**Comment by dylanmckay** [comment]
> Can we put this sort of thing in the Wiki or a standalone file?

I believe this is a fairly small task, and that is overkill.

**Comment by dylanmckay** [comment]
I had mistakenly closed the issue after I updated the tests to LLVM master, but the issues were still failing.

I have marked all failing tests as `XFAIL` so that they can be fixed.
