### ISSUE TITLE
Treat warnings as errors during CI?

### ISSUE THREAD

**Issue by RandomInsano** [avr-llvm/llvm#79]
I noticed we've got a few warning that might slip through the cracks. Shall I look into treating them as errors while building?

**Comment by RandomInsano** [comment]
If it's a good idea, #81 is ready to be merged. If not, close whenever.

**Comment by dylanmckay** [comment]
I think this is the right option.

**Comment by dylanmckay** [comment]
#81 is now merged :)

**Comment by dylanmckay** [comment]
I have reverted the commit in fa8aff1fcde66eb37cd2ca71e2d4ec0e8ef4994c.

There was a single error in LLVM mainline which was causing a travis build error (see travis [build #63](https://travis-ci.org/avr-llvm/llvm/builds/60161206)). We cannot depend on LLVM to be completely warning free.
