### ISSUE TITLE
Fix parsing of MOVW instruction

### ISSUE THREAD

**Issue by dylanmckay** [avr-llvm/llvm#84]
The `MOVW` instruction does not get parsed properly.

Once this instruction is fixed, take the `XFAIL` attribute from `test/MC/AVR/inst-movw.s`.

The AVR `gas` assembler syntax if full of ambiguities, which makes this difficult.

**Comment by agnat** [comment]
On the branch above the `movw` instruction is parsed and encoded correctly.
