### ISSUE TITLE
Implement jump tables

### ISSUE THREAD

**Issue by dylanmckay** [avr-llvm/llvm#88]
Implement [jump table](https://en.wikipedia.org/wiki/Branch_table) support.

**Comment by dylanmckay** [comment]
This blocks Arduino because `analogWrite` in `wiring_analoc.c` uses jump tables.

**Comment by dylanmckay** [comment]
I have disabled jump table emission in 177a73b6b81a3f631c17e4c3af36853b9873dada, so this no longer blocks Arduino.

**Comment by 4ntoine** [comment]
Will serial interruptions work? F.e. serial interruptions https://www.arduino.cc/en/Tutorial/SerialEvent

**Comment by dylanmckay** [comment]
Jump table emission is disabled - now switch statements are expanded into a set of `if-else` statements. This means that this issue does not stop any code from working.

w.r.t `SerialEvent` - it probably will not work. As stated in #149, `Serial.begin()` uses 32-bit division and so it will fail to compile (i.e. the bug you opened last).

**Comment by agnat** [comment]
What @dylanmckay says.

In general however interrupts _should_ work, if that is what you're asking. The interrupt table is not a jump table. "Should" as in I haven't actually tried it... ;)

**Comment by 4ntoine** [comment]
Oh, i see

**Comment by dylanmckay** [comment]
Heads up - #149 is now resolved!

**Comment by dylanmckay** [comment]
Jump tables is an optimisation, we can look into it in the future.

For now I'll close this and we can look into it in the distant future.
